services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tommypreel/fastapiapp:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
