name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Branche que vous utilisez pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key for Git
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 13.39.150.26
          username: ec2-user
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            # Stop and remove the existing container if it exists
            docker stop myfastapi || true
            docker rm myfastapi || true

            # Navigate to the application directory
            cd /home/ec2-user/myfastapiapp

            git pull origin main

            # Build the Docker image
            docker build -t myfastapi:latest .

            # Run the Docker container
            docker run -d --name myfastapi -p 8000:8000 -e AWS_REGION=${{ secrets.AWS_REGION }} \
             -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
             -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
             -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
              myfastapi:latest
