name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez pour le déploiement

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # utilisez la version Python nécessaire pour votre projet

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     source venv/bin/activate
    #     pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Attendez que le job de build-and-test soit terminé

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        ssh -i id_rsa -o StrictHostKeyChecking=no $USER@$HOST << EOF
          cd /home/***/myfastapiapp
          ls -l  # Vérifie le contenu du répertoire
          if [ -f docker-compose.yml ]; then
            docker-compose pull
            docker-compose up -d
          else
            echo "docker-compose.yml not found in /home/***/myfastapiapp"
            exit 1
          fi
        EOF
